language: python
python:
  - '3.6'

before_script:
  - pip install pipenv
  - pipenv install

env: DJANGO_SETTINGS_MODULE="pur_beurre_project.settings.travis"

services:
  - postgresql

script:
  - cd pur_beurre_project && pipenv run python manage.py test

branches:
  only:
    - master