language: python
python:
  - '3.5'

before_script:
  - pip install pipenv
  - pipenv install
  - psql -c 'create database travis_ci_test;' -U postgres

env: DJANGO_SETTINGS_MODULE="pur_beurre_project.settings.travis"

services:
  - postgresql

script:
  - pipenv run python manage.py test

  branches:
  only:
    - master